package it.polimi.ingsw.am32.client;

public enum Event {
    CREATE_GAME,
    JOIN_GAME,
    RECONNECT_GAME,
    PLACE_CARD,
    DRAW_CARD,
    SELECT_STARTER_CARD_SIDE,
    GAME_START,
    SELECT_GAME_MODE,
    GAME_PREPARATION,  LOBBY_CREATED_GAME,GAME_CREATED, NEW_PLAYER_JOIN, JOINED_GAME, WAITING_FOR_START
}
